const $=s=>document.querySelector(s);let selectedCode='';
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function status(s){$('#status').textContent=s;}
async function refresh(){try{const me=await api('/auth/me');$('#login').hidden=true;$('#account').hidden=false;$('#who').textContent=`Signed in as ${me.username}`;const d=await api('/auth/grants');$('#grants').replaceChildren();for(const g of d.grants){const row=document.createElement('div');row.className='grant';row.textContent=g.label;const b=document.createElement('button');b.textContent='Disconnect';b.onclick=async()=>{try{await api('/auth/revoke',{grant_id:g.id});await refresh();}catch(e){status(e.message)}};row.append(b);$('#grants').append(row);}}catch{$('#login').hidden=false;$('#account').hidden=true;}}
$('#login').onsubmit=async e=>{e.preventDefault();status('Signing in…');try{const f=new FormData(e.target);await api('/auth/login',{username:f.get('username'),password:f.get('password')});e.target.reset();if(location.pathname!='/connect'){location.replace('/');return;}status('');await refresh();}catch(e){status(e.message)}};
$('#logout').onclick=async()=>{await api('/auth/logout',{});location.replace('/login');};
$('#lookup').onsubmit=async e=>{e.preventDefault();try{selectedCode=new FormData(e.target).get('code').trim().toUpperCase();const d=await api('/auth/device-info?code='+encodeURIComponent(selectedCode));$('#client').textContent=`${d.label} requests access to:`;$('#scopes').replaceChildren();for(const s of d.scopes){const li=document.createElement('li');li.textContent=s;$('#scopes').append(li);}$('#consent').hidden=false;status('');}catch(e){status(e.message)}};
$('#approve').onclick=async()=>{try{await api('/auth/approve',{user_code:selectedCode});$('#consent').hidden=true;status('Connected. Return to LightMind.');setTimeout(refresh,6000);}catch(e){status(e.message)}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});refresh();
